apiVersion: apps/v1
kind: Deployment
metadata:
  name: writer-deployment
  labels:
    app: writer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: writer
  template:
    metadata:
      labels:
        app: writer
    spec:
      containers:
      - name: writer
        image: writer-image:2
        ports:
        - containerPort: 8000
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: user
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        - name: DB_HOST
          value: "mysql"
        - name: DB_NAME
          value: "testdb"
---
apiVersion: v1
kind: Service
metadata:
  name: writer
  labels:
    app: writer
spec:
  selector:
    app: writer
  ports:
    - protocol: TCP
      name: metrics
      port: 8000
      targetPort: 8000
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: writer-monitor
spec:
  selector:
    matchLabels:
      app: writer
  endpoints:
  - port: metrics
    interval: 15s
  targetLabels:
    - app